### ISSUE TITLE
Multiple errors sent, only one received

### ISSUE THREAD

**Issue by paul-uz** [MindscapeHQ/raygun4node#238] opened 2024-06-01 19:24 UTC
I am sending multiple errors in a test function on AWS Lambda and I am using the new `await` version of `send()` with batches disabled in the client.

I only see one error in raygun after running the function.

**Comment by miquelbeltran** [comment] 2024-06-02 12:30
Hi @paul-uz are the error instances grouped in Raygun?

**Comment by paul-uz** [comment] 2024-06-02 12:32
> Hi @paul-uz are the error instances grouped in Raygun?

No they weren't. I've tried to change to message based grouping and I think that helped a bit.

How up to date is the node hasher? It's on version 1 and the node package only just got an update in 2 years so maybe it needs some attention?

**Comment by miquelbeltran** [comment] 2024-06-02 12:40
Is there a change you can set the environment variable `DEBUG` to `raygun` and send us a log? The log should contain the lines `[raygun.ts] Successfully sent message ...` each time an error is sent using the `send()` method.

I need to check why the Raygun API is grouping errors even when the `error.message` is different.

**Comment by miquelbeltran** [comment] 2024-06-02 12:42
Can you also provide some sample code showing how you use the raygun client?

**Comment by paul-uz** [comment] 2024-06-04 15:18
Right, changed back to message based grouping, and triggered two different errors, and it seems to be working now?

Provider based grouping still seems broken.

**Comment by miquelbeltran** [comment] 2024-06-05 07:01
Thanks for checking! I asked the team to review the hasher algorithm for the node provider. I will leave this ticket open until there are more updates.

**Comment by sumitramanga** [comment] 2024-07-02 21:34
Hi team, sorry for the delay on this! I'm going to pass this onto this week's customer support engineer to take a look at this. Thanks so much for the additional context! We'll keep you well informed

**Comment by sumitramanga** [comment] 2024-07-10 09:21
Hi Team, 

We have an engineer looking into this issue. We'll let you know what we find based on our investigations. 

Thank you for your patience!

**Comment by sumitramanga** [comment] 2024-07-17 22:05
Hi team, this is still a work in progress at the moment. Replicating the issue is a bit of a tough one on our end but we'll continue to work away on this. Appreciate the patience! 

@paul-uz Can you please send through information on your project set up like the Node version you are using. This would be very helpful !

**Comment by Pallesen01** [comment] 2024-08-13 23:57
Hi @paul-uz, I've been unable to recreate this issue, would you be able to share anymore details about your test setup?

You could also try using our [raygun4node-aws-lambda ](https://github.com/MindscapeHQ/raygun4node-aws-lambda) provider and see if that resolves the issue.

**Comment by Pallesen01** [comment] 2024-08-27 01:07
Closing this as the issue can't be reproduced.

**Closed** 2024-08-27 01:08 UTC
Labels: bug
