### ISSUE TITLE
Request handler can causes 404 regardless of error 

### ISSUE THREAD

**Issue by christensena** [MindscapeHQ/raygun4node#93] opened 2020-09-29 03:58 UTC
We had a problem that took some time to track down and a lot of frustration.
We are using express in azure functions.
When an error occurred, it seemed like Azure was turning it into a 404 with an HTML response every time and swallowing the detail.

Eventually we found that by moving the raygun error handler to the very end of our middleware pipeline, the problem went away.

I think the culprit may be in this line
https://github.com/MindscapeHQ/raygun4node/blob/0191eb7fa1148aae95536149c8ead65853910d31/lib/raygun.ts#L297

Where the end of the handler is `next()` instead of `next(err)`.

If it was the latter, then the error could be captured separately or bubbled up to (in our case Azure functions logging). I don't think raygun should be swallowing the error.

**Comment by Widdershin** [comment] 2020-09-29 04:29
Thanks for the report. This looks like a regression, I'll try to get a fix out ASAP.

**Comment by Widdershin** [comment] 2020-09-29 04:49
@christensena I've just published `v0.12.2` which includes a fix for this issue.

I'm sorry that this issue caused frustration, and I appreciate the detailed bug report. Unfortunately, I introduced this issue while refactoring the project to use TypeScript. We now have a proper test case for this behaviour though, so it shouldn't break in future.

Please let me know if you run into any more issues!

**Comment by christensena** [comment] 2020-09-29 22:30
Appreciate the quick response!

**Closed** 2020-09-30 01:08 UTC
